//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFileSortingWPF.settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    public sealed partial class w_appsetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static w_appsetting defaultInstance = ((w_appsetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new w_appsetting())));
        
        public static w_appsetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DelPathOnSort {
            get {
                return ((bool)(this["DelPathOnSort"]));
            }
            set {
                this["DelPathOnSort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludePathOnAdd {
            get {
                return ((bool)(this["IncludePathOnAdd"]));
            }
            set {
                this["IncludePathOnAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>yyyy-MM</string>
  <string>yy-MM</string>
  <string>MM-yyyy</string>
  <string>MM-yy</string>
  <string>yyyy</string>
  <string>MMMM-yyyy</string>
  <string>yyyy-MMMM</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DateFormat {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DateFormat"]));
            }
            set {
                this["DateFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedDateFormat {
            get {
                return ((string)(this["SelectedDateFormat"]));
            }
            set {
                this["SelectedDateFormat"] = value;
            }
        }
    }
}
